In [1]:
import numpy as np


In [2]:
list=[10, 20, 30, 40]

arr=np.array(list)

print(arr)

[10 20 30 40]


In [3]:
print(arr.ndim)

1


In [4]:
print(arr.shape)

(4,)


In [9]:
list1=[[1,2,3,4], [5,6,7,8]]

arr=np.array(list1)

print(arr)

print(arr.ndim)

print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [11]:
arr=np.arange(0,6)

print(arr)

[0 1 2 3 4 5]


In [12]:
arr=np.arange(1,50,5)

print(arr)

[ 1  6 11 16 21 26 31 36 41 46]


In [14]:
arr=np.arange(1,7).reshape(2,3)

print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
arr=np.arange(0,100,5).reshape(4,5)

print(arr)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


In [18]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, s

In [19]:
#linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [21]:
arr=np.linspace(0,11, num=50, dtype=int)

print(arr)

[ 0  0  0  0  0  1  1  1  1  2  2  2  2  2  3  3  3  3  4  4  4  4  4  5
  5  5  5  6  6  6  6  6  7  7  7  7  8  8  8  8  8  9  9  9  9 10 10 10
 10 11]


In [22]:
arr=np.linspace(1, 50, 20, endpoint=False, retstep=True)

print(arr)

(array([ 1.  ,  3.45,  5.9 ,  8.35, 10.8 , 13.25, 15.7 , 18.15, 20.6 ,
       23.05, 25.5 , 27.95, 30.4 , 32.85, 35.3 , 37.75, 40.2 , 42.65,
       45.1 , 47.55]), 2.45)


In [25]:
arr=np.linspace(1, 50, 20).reshape(5,4)

print(arr)

[[ 1.          3.57894737  6.15789474  8.73684211]
 [11.31578947 13.89473684 16.47368421 19.05263158]
 [21.63157895 24.21052632 26.78947368 29.36842105]
 [31.94736842 34.52631579 37.10526316 39.68421053]
 [42.26315789 44.84210526 47.42105263 50.        ]]


In [27]:
help(np.logspace)

Help on _ArrayFunctionDispatcher in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.25.0
        Non-scalar 'base` is now supported
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
  

In [28]:
#logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)

In [29]:
arr=np.logspace(0, 50)

print(arr)

[1.00000000e+00 1.04811313e+01 1.09854114e+02 1.15139540e+03
 1.20679264e+04 1.26485522e+05 1.32571137e+06 1.38949549e+07
 1.45634848e+08 1.52641797e+09 1.59985872e+10 1.67683294e+11
 1.75751062e+12 1.84206997e+13 1.93069773e+14 2.02358965e+15
 2.12095089e+16 2.22299648e+17 2.32995181e+18 2.44205309e+19
 2.55954792e+20 2.68269580e+21 2.81176870e+22 2.94705170e+23
 3.08884360e+24 3.23745754e+25 3.39322177e+26 3.55648031e+27
 3.72759372e+28 3.90693994e+29 4.09491506e+30 4.29193426e+31
 4.49843267e+32 4.71486636e+33 4.94171336e+34 5.17947468e+35
 5.42867544e+36 5.68986603e+37 5.96362332e+38 6.25055193e+39
 6.55128557e+40 6.86648845e+41 7.19685673e+42 7.54312006e+43
 7.90604321e+44 8.28642773e+45 8.68511374e+46 9.10298178e+47
 9.54095476e+48 1.00000000e+50]


In [31]:
arr=np.logspace(0, 50, num=20,  dtype=int)

print(arr)

[          1         428      183298    78475997 -2147483648 -2147483648
 -2147483648 -2147483648 -2147483648 -2147483648 -2147483648 -2147483648
 -2147483648 -2147483648 -2147483648 -2147483648 -2147483648 -2147483648
 -2147483648 -2147483648]


In [32]:
arr=np.logspace(0,100, num=20, dtype=int).reshape(4,5)

print(arr)

[[          1      183298 -2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648 -2147483648 -2147483648]]


In [34]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [36]:
arr=np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
arr=np.zeros((4,3), dtype=int)

print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [39]:
arr=np.ones((4,5), dtype=int)

print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [40]:
arr=np.identity(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
arr=np.identity(5, dtype=int)

print(arr)

print(arr.ndim)

print(arr.shape)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
2
(5, 5)


In [45]:
arr=np.eye(3,2)

print(arr)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [46]:
arr=np.eye(4,5, k=1)

print(arr)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [47]:
arr=np.eye(4,5, k=2)

print(arr)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [48]:
arr=np.random.rand(3)

print(arr)

[0.31334544 0.42418813 0.48235688]


In [49]:
arr=np.random.rand(4,3)

print(arr)

[[0.70943216 0.4117969  0.81351644]
 [0.39016159 0.71087169 0.62883563]
 [0.34495306 0.8080603  0.77058288]
 [0.57890639 0.22941319 0.31788906]]


In [50]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer t

In [51]:
#randint(low, high=None, size=None, dtype=int)

In [54]:
arr=np.random.randint(0, 100, size=(2))

print(arr)

[ 1 95]


In [56]:
arr=np.random.randint(0, 100, size=(4,5))

print(arr)

[[68 63 81 62 98]
 [36 96 68 32 15]
 [ 6 36 82 28 20]
 [85 32 69 89 83]]


In [57]:
#Numpy Array Indexing

In [61]:
arr=np.arange(0,6)

print(arr)

print(arr[3])

print(arr[-1])


print(arr[2:-2])

[0 1 2 3 4 5]
3
5
[2 3]


In [67]:
arr=np.arange(0,6).reshape(3,2)

print(arr)

print()

print(arr[2])

print()

print(arr[2,1])

print()

print(arr[1:,:])

[[0 1]
 [2 3]
 [4 5]]

[4 5]

5

[[2 3]
 [4 5]]


In [77]:
arr=np.arange(0,9).reshape(3,3)

print(arr)

print()

print(arr[1:,1:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[4 5]
 [7 8]]


In [81]:
arr=np.arange(0,9)

print(arr)

print()

ad=arr>5
print(ad)

print()

print(arr[ad])

[0 1 2 3 4 5 6 7 8]

[False False False False False False  True  True  True]

[6 7 8]


In [82]:
#Numpy operations


In [94]:
arr=np.arange(0,11)

print(arr)

print(arr+arr)

print(arr*arr)

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[  0   1   4   9  16  25  36  49  64  81 100]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


C:\Users\Milan\AppData\Local\Temp\ipykernel_33048\3487513948.py:15: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [92]:
arr1=np.arange(0,11)

arr2=np.arange(12,23)

print(arr1)

print(arr2)

print(arr1+arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[12 13 14 15 16 17 18 19 20 21 22]
[12 14 16 18 20 22 24 26 28 30 32]
